import { Router } from 'express';
import { getAssignedClasses, getClassDetail, submitAttendance, getAttendanceLogs, createAssessment, getAssessments, submitMarks, getStudentMarks, getAtRiskStudents, getFacultyTimetable, } from '../controllers/faculty.controller.js';
import { authenticate } from '../middleware/auth.js';
import { requireRole } from '../middleware/rbac.js';
import { UserRole } from '@campusgent/shared';
const router = Router();
// Apply auth and role protection specifically for Faculty, Admin, and Super Admin roles
router.use(authenticate);
router.use(requireRole([UserRole.FACULTY, UserRole.ADMIN, UserRole.SUPER_ADMIN]));
router.get('/classes', getAssignedClasses);
router.get('/classes/:classId', getClassDetail);
router.post('/attendance', submitAttendance);
router.get('/attendance', getAttendanceLogs);
router.post('/assessments', createAssessment);
router.get('/assessments', getAssessments);
router.post('/marks', submitMarks);
router.get('/marks', getStudentMarks);
router.get('/at-risk', getAtRiskStudents);
router.get('/timetable', getFacultyTimetable);
export default router;
