import { Router } from 'express';
import authRoutes from './auth.routes.js';
import studentRoutes from './student.routes.js';
import jobRoutes from './job.routes.js';
import analyticsRoutes from './analytics.routes.js';
import notificationRoutes from './notification.routes.js';
import aiRoutes from './ai.routes.js';
import agentRoutes from './agent.routes.js';
import mockInterviewRoutes from './mock-interview.routes.js';
import facultyRoutes from './faculty.routes.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
router.use('/jobs', jobRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/ai', aiRoutes);
router.use('/agents', agentRoutes);
router.use('/mock-interviews', mockInterviewRoutes);
router.use('/faculty', facultyRoutes);
export default router;
